-- Garante todos os campos exigidos pelo mapeamento JPA da entidade Estoque
ALTER TABLE estoque
    ADD COLUMN IF NOT EXISTS produto_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS localizacao VARCHAR(255),
    ADD COLUMN IF NOT EXISTS data_ultima_entrada DATETIME,
    ADD COLUMN IF NOT EXISTS data_ultima_saida DATETIME,
    ADD COLUMN IF NOT EXISTS observacoes VARCHAR(255),
    ADD COLUMN IF NOT EXISTS version BIGINT,
    ADD COLUMN IF NOT EXISTS data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS data_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
