-- Garante os campos de auditoria para a entidade Estoque
ALTER TABLE estoque
    ADD COLUMN IF NOT EXISTS data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE estoque
    ADD COLUMN IF NOT EXISTS data_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
