INSERT INTO roles (nome) VALUES ('ROLE_ADMIN');
INSERT INTO roles (nome) VALUES ('ROLE_COMPRADOR');
INSERT INTO roles (nome) VALUES ('ROLE_SOLICITANTE');
INSERT INTO roles (nome) VALUES ('ROLE_APROVADOR');
INSERT INTO roles (nome) VALUES ('ROLE_ALMOXARIFE');